---
galaxy_info:
  role_name: common
  author: cadiguni
  description: Pacotes base e utilitarios comuns a todas as distros
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: Fedora
      versions: [all]
    - name: EL
      versions: [all]
    - name: Archlinux
      versions: [all]
    - name: opensuse
      versions: [all]
  galaxy_tags:
    - workstation
    - devops

dependencies: []
