---
flatpak_apps_packages:
  - com.obsproject.Studio
  - org.audacityteam.Audacity
  - org.godotengine.Godot
  - com.valvesoftware.Steam
  - com.getpostman.Postman
  - com.discordapp.Discord

flatpak_apps_remove_packages: []
