---
dev_tools_install_dotnet: true
dev_tools_install_node: true
dev_tools_install_mise: true

dev_tools_npm_global_packages:
  - azure-functions-core-tools@4

dev_tools_pipx_packages:
  - ansible-lint
  - pre-commit
  - httpie
