---
server_base_configure_firewall: true
server_base_install_fail2ban: true
server_base_configure_ssh: true
server_base_configure_ntp: true
server_base_install_unattended_upgrades: true

server_base_extra_packages: []

server_base_firewall_allowed_tcp_ports:
  - 22

server_base_ssh_permit_root_login: "no"
server_base_ssh_password_authentication: "no"
server_base_ssh_max_auth_tries: 4
server_base_ssh_client_alive_interval: 300
server_base_ssh_x11_forwarding: "no"
