---
- name: Adicionar Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Instalar apps graficos via Flatpak
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
  when: flatpak_packages | length > 0

- name: Remover apps Flatpak indesejados
  community.general.flatpak:
    name: "{{ flatpak_remove_packages }}"
    state: absent
  when: flatpak_remove_packages | length > 0
