---
common_packages:
  - bash-completion
  - ca-certificates
  - curl
  - flatpak
  - gcc
  - gcc-c++
  - git
  - htop
  - jq
  - make
  - mtr
  - ncdu
  - p7zip
  - p7zip-plugins
  - python3
  - python3-pip
  - tree
  - unzip
  - wget
  - zip
  - zsh

common_java_package: >-
  {{
    'java-latest-openjdk-devel'
    if ansible_distribution == 'Fedora'
    and (ansible_distribution_major_version | int) >= 44
    else 'java-21-openjdk-devel'
  }}
