---
common_packages:
  - bash-completion
  - bind-utils
  - ca-certificates
  - curl
  - flatpak
  - gcc
  - gcc-c++
  - git
  - git-lfs
  - htop
  - iotop
  - jq
  - lsof
  - make
  - mtr
  - ncdu
  - net-tools
  - openssh-clients
  - p7zip
  - p7zip-plugins
  - pipx
  - python3
  - python3-pip
  - rsync
  - tmux
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - zip
  - zsh

common_java_package: >-
  {{
    'java-latest-openjdk-devel'
    if ansible_distribution == 'Fedora'
    and (ansible_distribution_major_version | int) >= 44
    else 'java-21-openjdk-devel'
  }}
