---
common_packages:
  - bash-completion
  - ca-certificates
  - curl
  - flatpak
  - gcc
  - gcc-c++
  - git
  - htop
  - java-21-openjdk-devel
  - jq
  - make
  - mtr
  - ncdu
  - p7zip
  - p7zip-plugins
  - python3
  - python3-pip
  - tree
  - unzip
  - wget
  - zip
  - zsh
